// 新增 buildscript
buildscript {
    dependencies {
        // Note: If you use HuaWei or Honor push, you need to add the following dependencies
        classpath("com.android.tools.build:gradle:8.6.1")
        classpath("io.codearte.gradle.nexus:gradle-nexus-staging-plugin:0.22.0")
    }
}
plugins {
    id 'com.android.application' version '8.6.1' apply false
    id 'com.android.library' version '8.6.1' apply false
}

ext{
    if(!project.hasProperty('sdkVersion')){
        sdkVersion = '3.2.3'
    }
    if(!project.hasProperty('stagingRepositoryId')){
        stagingRepositoryId = 'iohyphenate-1000'
    }
}

if (JavaVersion.current().isJava8Compatible()) {
    allprojects {
        tasks.withType(Javadoc) {
            options.addStringOption('Xdoclint:none', '-quiet')
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

apply plugin: 'io.codearte.nexus-staging'

//tasks.getByPath(":ease-call-kit:javadoc").enabled = false